### ISSUE TITLE
Need to press Tab twice to move to the next button in the styling demo (Firefox)

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-button#20]
Sometimes I need to press the Tab key twice on each button to move the focus to the next button. Moving focus to the previous button only requires one Shift-Tab press at https://cdn.vaadin.com/vaadin-button/1.0.0-alpha1/demo/styling.html

It seems to happen most reliably when I first tab through the buttons backwards with Shift-Tab, and then try to tab through then forwards.

Only happens in Firefox.

**Comment by tomivirkki** [comment]
Might be the same issue as https://github.com/vaadin/vaadin-text-field/issues/71. Since the fix was done in the vaadin-control-state-mixin (https://github.com/vaadin/vaadin-control-state-mixin/pull/3), it should apply to button also. Have you tried with the latest version of vaadin-control-state-mixin?

**Comment by jouni** [comment]
Nope, just tried with the CDN version.

**Comment by jouni** [comment]
Indeed, fixed in master.
