### ISSUE TITLE
Why not extends HTMLButtonElement?

### ISSUE THREAD

**Issue by abdonrd** [vaadin/vaadin-button#36]
Something like:

```html
<link rel="import" href="../polymer/lib/mixins/element-mixin.html">
<link rel="import" href="../vaadin-themable-mixin/vaadin-themable-mixin.html">

<dom-module id="vaadin-button">
  <template>
    <slot></slot>
  </template>
  <script>
    if (!Polymer.ElementMixin) {
      throw new Error(`Unexpected Polymer version ${Polymer.version} is used, expected v2.0.0 or later.`);
    }

    (function() {
      class ButtonElement extends Vaadin.ThemableMixin(
        Polymer.ElementMixin(HTMLButtonElement)
      ) {
        static get is() {
          return 'vaadin-button';
        }
      }

      customElements.define(ButtonElement.is, ButtonElement);

      /**
       * @namespace Vaadin
       */
      window.Vaadin = window.Vaadin || {};
      Vaadin.ButtonElement = ButtonElement;
    })();
  </script>
</dom-module>
```

**Comment by limonte** [comment]
Thanks for the good question @abdonrd 

It seems that it's not possible to extend the `HTMLButtonElement`: https://jsfiddle.net/6r5htd05/13/

I'm getting the `Uncaught TypeError: Illegal constructor` exception. It's interesting that it's possible to extend  the `HTMLElement`: https://jsfiddle.net/6r5htd05/14/

This issue is probably related to your question: https://github.com/Polymer/polymer/issues/3925

**Comment by abdonrd** [comment]
@limonte oh, right! 😮 

I'm getting the same `Uncaught TypeError: Illegal constructor` exception without without `Polymer.ElementMixin`: https://jsfiddle.net/w7j5bqvn/

Thanks!

**Comment by limonte** [comment]
Yup, looks like a restriction we can't bypass for now.
