### ISSUE TITLE
Button size in determined incorrectly in IE11 and EdgeHTML14 (ShadyCSS)

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-button#63]
_From @vlukashov on November 30, 2017 9:59_

When using the Lumo (prev. Valo) theme for a `<vaadin-button>` in IE11, the height of the button is determined differently than in other browsers (tested Firefox, Chrome, Safari and Edge).

For example, see a comparison to Firefox:
![valo-button-sizing](https://user-images.githubusercontent.com/22416150/33424770-7f1d5af2-d5c5-11e7-9061-1c4b57ec4d92.png)

It looks like in IE11 the `--lumo-button-size` (prev `--valo-size`) custom property gets defined when it was not supposed to.
A live demo is here: https://vlukashov.github.io/vaadin-valo-button-sizing/ (source code at https://github.com/vlukashov/vaadin-valo-button-sizing/)

_Copied from original issue: vaadin/vaadin-valo-styles#38_

**Comment by jouni** [comment]
Sounds like a ShadyCSS issue. Need to investigate.

Any ideas why this does not happen in the demo? You need to run it locally to test in IE11 because it’s not transpiled in our CDN.

**Comment by jouni** [comment]
Side note: the `--valo-size` property/concept is not yet really fully formed, and subject to change.

**Comment by jouni** [comment]
I’ve witnessed this myself now also. For some reason it only happens on some pages, and only affects the first button on the page.

The incorrect size comes from the `theme="large"` variant styles, which sets the button size to `--valo-size-l` (44px).

**Comment by jouni** [comment]
I’m considering dropping the current `--lumo-button-size` property, which should resolve this issue.

**Comment by jouni** [comment]
Interestingly, similar approach in `vaadin-text-field` does not cause problems:
- Introducing the `--lumo-text-field-size` property: https://github.com/vaadin/vaadin-text-field/blob/master/theme/lumo/vaadin-text-field.html#L11
- Resetting the property to a smaller size: https://github.com/vaadin/vaadin-text-field/blob/master/theme/lumo/vaadin-text-field.html#L293

**Comment by web-padawan** [comment]
Fixed by webcomponents/shadycss#169 which has been shipped in `webcomponentsjs` v1.1.1
I have tried installing different versions of polyfill and I was able to confirm the fix.

Before (webcomponentsjs v1.1.0):
<img width="259" alt="screen shot 2018-03-22 at 22 04 36" src="https://user-images.githubusercontent.com/10589913/37795412-10349dc0-2e1d-11e8-88b6-68591d2ed134.png">

After (webcomponentsjs v1.1.0):
<img width="259" alt="screen shot 2018-03-22 at 22 04 21" src="https://user-images.githubusercontent.com/10589913/37795432-205d9b3e-2e1d-11e8-9dc0-e21d93d57f7d.png">
